apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:
  containers:
  - name: hello-world
    image: non-existent-image-fe23gf:latest
    command: ["echo", "Hello, World!"]
  restartPolicy: Never

  
